### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by aspiers** [lxsli/ansible-viz#3]
Hi there, thanks a lot for sharing this code!  Even if it's currently considered a dead project, I managed to make [a bunch of fixes and enhancements](https://github.com/lxsli/ansible-viz/compare/master...aspiers:fixes?expand=1) and get it plotting some pretty useful graphs.

I would like to share my changes in a way others can use.  Would you be interested in reviving the project?  If so I would be happy to submit pull requests and issues.  Or if not not, maybe I could take over maintainership instead, at least in the short term?

Thanks again!

**Comment by elzibubble** [comment]
Hey, I'm glad you like it. If you want to take over maintainership, please go ahead. I'll merge a PR to point the readme at your version if you submit one.

**Comment by aspiers** [comment]
Thanks a lot! I'll do that.
